from enum import Enum


class TokenTypeModel(str, Enum):
    ACCESS_TOKEN = "ACCESS_TOKEN"
    REFRESH_TOKEN = "REFRESH_TOKEN"
    EMAIL_VERIFICATION_TOKEN = "EMAIL_VERIFICATION_TOKEN"
    PASSWORD_RESET_TOKEN = "PASSWORD_RESET_TOKEN"
